#define Flavor "gabbo-rpg"
#include <flavor_config.h>

#define CartesianRoomCode    ModulesDir "/room_cartesian"
#define CommandCode          ModulesDir "/command"
#define ContainerCode        ModulesDir "/container"
#define CreatureCode         ModulesDir "/creature"
#define OrganismCode         ModulesDir "/organism"
#define RoomCode             ModulesDir "/room"
#define SphericalRoomCode    ModulesDir "/room_spherical"
#define StuffCode            ModulesDir "/stuff"
#define ThingCode            ModulesDir "/thing"
#define VehicleCode          ModulesDir "/vehicle"

#define CarrierMixin         ModulesDir "/carrier"
#define CommandGiverMixin    ModulesDir "/command_giver"
#define DetailMixin          ModulesDir "/detail"
#define IdMixin              ModulesDir "/id"
#define LockMixin            ModulesDir "/lock"
#define MobileMixin          ModulesDir "/mobile"
#define NameMixin            ModulesDir "/name"
#define PreferencesMixin     ModulesDir "/preferences"
#define PropertyMixin        ModulesDir "/property"
#define SensorMixin          ModulesDir "/sensor"
#define ShellMixin           ModulesDir "/shell"
#define SoulMixin            ModulesDir "/soul"
#define SpeechMixin          ModulesDir "/speech"
#define VisibleMixin         ModulesDir "/visible"

#define Avatar               ObjDir "/avatar"
#define CodeHostController   ObjDir "/codehost_controller"

#define OrganismsDir         ModulesDir "/organisms"
