#define Flavor "gabbo-rpg"
#include <flavor_config.h>

#define RoomCode             ModulesDir "/room"
#define CartesianRoomCode    ModulesDir "/room_cartesian"
#define SphericalRoomCode    ModulesDir "/room_spherical"
#define StuffCode            ModulesDir "/stuff"
#define ThingCode            ModulesDir "/thing"
#define OrganismCode         ModulesDir "/organism"
#define CreatureCode         ModulesDir "/creature"
#define ContainerCode        ModulesDir "/container"
#define CommandCode          ModulesDir "/command"
#define VehicleCode          ModulesDir "/vehicle"

#define IdMixin              ModulesDir "/id"
#define NameMixin            ModulesDir "/name"
#define DetailMixin          ModulesDir "/detail"
#define VisibleMixin         ModulesDir "/visible"
#define PropertyMixin        ModulesDir "/property"
#define ShellMixin           ModulesDir "/shell"
#define CommandGiverMixin    ModulesDir "/command_giver"
#define LockMixin            ModulesDir "/lock"
#define MobileMixin          ModulesDir "/mobile"

#define LoggerFactory        ObjDir "/logger_factory"
#define LoginObject          ObjDir "/auth/login"
#define Avatar               ObjDir "/avatar"
#define CodeHostController   ObjDir "/codehost_controller"

#define OrganismsDir         ModulesDir "/organisms"
