#define Flavor "gabbo-basic"
#include <flavor_config.h>

#define CartesianRoomCode    ModuleDir "/room_cartesian"
#define ContainerCode        ModuleDir "/container"
#define CreatureCode         ModuleDir "/creature"
#define OrganismCode         ModuleDir "/organism"
#define HumanCode            ModuleDir "/human"
#define RoomCode             ModuleDir "/room"
#define SphericalRoomCode    ModuleDir "/room_spherical"
#define StuffCode            ModuleDir "/stuff"
#define ThingCode            ModuleDir "/thing"
#define VehicleCode          ModuleDir "/vehicle"

#define CarrierMixin         ModuleDir "/carrier"
#define CharacterMixin       ModuleDir "/character"
#define DetailMixin          ModuleDir "/detail"
#define IdMixin              ModuleDir "/id"
#define LiteracyMixin        ModuleDir "/literacy"
#define LockMixin            ModuleDir "/lock"
#define MobileMixin          ModuleDir "/mobile"
#define NameMixin            ModuleDir "/name"
#define PreferencesMixin     ModuleDir "/preferences"
#define SpeechMixin          ModuleDir "/speech"
#define VisibleMixin         ModuleDir "/visible"

#define Avatar               ObjDir "/avatar"
#define CodeHostController   ObjDir "/codehost_controller"

#define OrganismsDir         ModuleDir "/organisms"
